//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.tMemberships = new HashSet<tMembership>();
            this.tUserProfiles = new HashSet<tUserProfile>();
            this.tVehicleProfileControls = new HashSet<tVehicleProfileControl>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.tPosts = new HashSet<tPost>();
            this.tFeedbacks = new HashSet<tFeedback>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CodeId { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<tMembership> tMemberships { get; set; }
        public virtual ICollection<tUserProfile> tUserProfiles { get; set; }
        public virtual ICollection<tVehicleProfileControl> tVehicleProfileControls { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<tPost> tPosts { get; set; }
        public virtual tTestingCode tTestingCode { get; set; }
        public virtual ICollection<tFeedback> tFeedbacks { get; set; }
    }
}
