//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dboMyJeepTraderEntities : DbContext
    {
        public dboMyJeepTraderEntities()
            : base("name=dboMyJeepTraderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tAccount> tAccounts { get; set; }
        public virtual DbSet<tImageControl> tImageControls { get; set; }
        public virtual DbSet<tImage> tImages { get; set; }
        public virtual DbSet<tMembership> tMemberships { get; set; }
        public virtual DbSet<tPost> tPosts { get; set; }
        public virtual DbSet<tPostsControl> tPostsControls { get; set; }
        public virtual DbSet<tUserProfile> tUserProfiles { get; set; }
        public virtual DbSet<tVehicleProfileControl> tVehicleProfileControls { get; set; }
        public virtual DbSet<tVehicleProfile> tVehicleProfiles { get; set; }
    }
}
