//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCity
    {
        public tCity()
        {
            this.tPosts = new HashSet<tPost>();
        }
    
        public int CityId { get; set; }
        public string City { get; set; }
        public string ZIP { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual tState tState { get; set; }
        public virtual ICollection<tPost> tPosts { get; set; }
    }
}
