//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLocation
    {
        public tLocation()
        {
            this.tPosts = new HashSet<tPost>();
        }
    
        public int LocationId { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual ICollection<tPost> tPosts { get; set; }
    }
}
