//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMention
    {
        public int MentionId { get; set; }
        public string MentionedUserId { get; set; }
        public string MentionedByUserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CommentId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
