//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMessageControl
    {
        public int MessageControlId { get; set; }
        public string ToUserId { get; set; }
        public string FromUserId { get; set; }
        public Nullable<int> MessageId { get; set; }
    
        public virtual tMessage tMessage { get; set; }
    }
}
