//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tModel
    {
        public tModel()
        {
            this.tModelControls = new HashSet<tModelControl>();
            this.tModelYearControls = new HashSet<tModelYearControl>();
            this.tSubModels = new HashSet<tSubModel>();
        }
    
        public int ModelId { get; set; }
        public string Model { get; set; }
        public Nullable<int> MakeId { get; set; }
    
        public virtual tMake tMake { get; set; }
        public virtual ICollection<tModelControl> tModelControls { get; set; }
        public virtual ICollection<tModelYearControl> tModelYearControls { get; set; }
        public virtual ICollection<tSubModel> tSubModels { get; set; }
    }
}
