//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tModelPostControl
    {
        public int ModelPostControlId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> PostId { get; set; }
    
        public virtual tModel tModel { get; set; }
        public virtual tPost tPost { get; set; }
    }
}
