//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPost
    {
        public tPost()
        {
            this.tImageControls = new HashSet<tImageControl>();
            this.tPostsControls = new HashSet<tPostsControl>();
        }
    
        public int PostId { get; set; }
        public string PostTitle { get; set; }
        public string PostDescription { get; set; }
        public Nullable<bool> Part { get; set; }
        public string PartType { get; set; }
        public string PartBrand { get; set; }
        public string PartName { get; set; }
        public Nullable<bool> Vehicle { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public Nullable<System.DateTime> VehicleYear { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual ICollection<tImageControl> tImageControls { get; set; }
        public virtual tLocation tLocation { get; set; }
        public virtual ICollection<tPostsControl> tPostsControls { get; set; }
    }
}
