//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSetting
    {
        public int SettingsId { get; set; }
        public string Id { get; set; }
        public bool Posts { get; set; }
        public bool Status { get; set; }
        public bool Friends { get; set; }
        public bool Discover { get; set; }
        public bool PrivateStatus { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
