//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStatusControl
    {
        public int StatusControlId { get; set; }
        public string LikedBy { get; set; }
        public string DisLikedBy { get; set; }
        public int StatusId { get; set; }
    
        public virtual tStatusUpdate tStatusUpdate { get; set; }
    }
}
