//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tState
    {
        public tState()
        {
            this.tCities = new HashSet<tCity>();
            this.tPosts = new HashSet<tPost>();
        }
    
        public int StateId { get; set; }
        public string StateCode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<tCity> tCities { get; set; }
        public virtual ICollection<tPost> tPosts { get; set; }
    }
}
