//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSubscriptionType
    {
        public tSubscriptionType()
        {
            this.tSubscriptions = new HashSet<tSubscription>();
        }
    
        public int SubscriptionTypeId { get; set; }
        public string SubscriptionType { get; set; }
    
        public virtual ICollection<tSubscription> tSubscriptions { get; set; }
    }
}
