//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSubscription
    {
        public int SubscriptionId { get; set; }
        public int SubscriptionTypeId { get; set; }
        public Nullable<int> MembershipId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<bool> AutoRenew { get; set; }
        public Nullable<bool> Expired { get; set; }
    
        public virtual tMembership tMembership { get; set; }
        public virtual tSubscriptionType tSubscriptionType { get; set; }
    }
}
