//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserProfile
    {
        public int UserProfileId { get; set; }
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] Avatar { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string GooglePlus { get; set; }
        public string Twitter { get; set; }
        public string Ello { get; set; }
        public Nullable<long> ViewCount { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
