//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVehicleProfile
    {
        public tVehicleProfile()
        {
            this.tVehicleProfileControls = new HashSet<tVehicleProfileControl>();
        }
    
        public int VehicleProfileId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Manufacturer { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tVehicleProfileControl> tVehicleProfileControls { get; set; }
    }
}
