//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJeepTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVehicleProfileControl
    {
        public int VehicleProfileControlId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> VehicleProfileId { get; set; }
    
        public virtual tAccount tAccount { get; set; }
        public virtual tVehicleProfile tVehicleProfile { get; set; }
    }
}
